version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: blood-donation-security-app
    ports:
      - "443:443"
    env_file:
      - .env

volumes:
  mysql_data:
    external: false
